name: tezda_test
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  dio: ^5.5.0+1
  shared_preferences: ^2.2.3
  cached_network_image: ^3.3.1
  firebase_core: ^2.24.2
  rx_bloc: ^5.0.3
  flutter_rx_bloc: ^6.1.1
  json_annotation: ^4.9.0
  google_fonts: ^6.2.1
  rxdart: ^0.27.7
  provider: ^6.1.2
  auto_route: ^8.3.0
  firebase_auth: ^4.20.0 
  gap: ^3.0.1
  font_awesome_flutter: ^10.7.0
  cloud_firestore: ^4.17.5
  fluttertoast: ^8.2.6
  flutter_spinkit: ^5.2.1

dev_dependencies:
  rx_bloc_generator: ^7.2.2
  build_runner: ^2.4.11
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  json_serializable: ^6.8.0
  auto_route_generator: ^8.1.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/gif/
    - assets/icons/